project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    # toc: true

website:
  twitter-card: false
  open-graph: false
  # repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "http://github.com/xl0/ready-steady-go/"

  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]